services:
  - type: web
    name: Eng_zarur_ilm_bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TIMEZONE
        value: Asia/Tashkent
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: ADMIN_IDS
        sync: false
      - key: WEBAPP_URL
        sync: false
      - key: DATABASE_URL
        sync: false
